### ISSUE TITLE
Eksportjobb for bounding bokser

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#10]
Alle lag ut i 1 .json-fil

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/25771dc5bf5b26aa55b8d881d01c4d0e52fc85cb

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/dd3970c9782d661f67884bb4bf5c96284268ec90
