### ISSUE TITLE
import naturvernområder

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/grunnkart-dataflyt#11]
Hent fra: https://kartkatalog.miljodirektoratet.no/Dataset/Details/0

Foreslår at vi bruker: http://trdefme02.miljodirektoratet.no/nedlasting/Naturbase/Shape/naturvern_utm33.zip

Etablerer rutiner for oppdatering (f.eks 1 dag hver måned)

Samme issue ligger her: https://github.com/Artsdatabanken/ratatouille/issues/245

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/4a0e00aa34601de94597a173f142e831ba9f3b54
