### ISSUE TITLE
Importjobb administrative områder

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/grunnkart-dataflyt#12]
Etablere rutiner for import/oppdatering av all administrativ geometri i basen (kommune/fylke). Avklar med øvrig bruk av administrativ geometri i andre fagsystem i ADB.

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/e73fa68c585bdbc18c8f9def299dbfdcccfb26bf
