### ISSUE TITLE
Metadata exceeds limit of 60kb. 

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#13]
Tile set: naturomrader9-bfrgpe

Metadata exceeds limit of 60kb | The TileJSON file in your MBTiles upload contains too much information. | Remove extra or unneeded content from the TileJSON file (inside the MBTiles file).
-- | -- | --

**Comment by jarped** [comment]
Fikset av naturomrader9-5p772q
