### ISSUE TITLE
Lastejobb som oppretter tomt databaseskjema postgresql

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#2]
Jobb som oppretter nødvendig schema, og tabeller for databasen. 

Innhold (logisk sett)
 - Tabell for Geometri
 - Tabell for Kode
 - Tabell for Kodetre
 - Tabell for Datasett
 - Relasjoner Geometri - Kode
 - Relasjoner Geometri - Datasett
 - Relasjoner Kode --> koden og alle overordnede koder

**Comment by jarped** [comment]
Databaseskjema:
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/9dda83a0a1cd7c564d8a07a6219e3197b97c9c9f

**Comment by jarped** [comment]
Lastescript:
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/b1b7bfd5ddea2e8fe2aa49f60ad9e3ac9fa8ff37
