### ISSUE TITLE
Lag statistikk for koder

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#23]
1 json per kode (verneområde, kommune, fylke + evt.)

```json
{
  "MI_KA": {"MI_KA-1": 0.2, "MI_KA-2": 0.8},
  "NA": {"NA_T": 0.1, "NA_V": 0.9}
}
```

Depends on [github/kverna#55](https://github.com/Artsdatabanken/kverna/issues/55)

**Comment by runningbones** [comment]
per areal

**Comment by bjornreppen** [comment]
Nå løst med eget API: https://github.com/Artsdatabanken/romlig-api
