### ISSUE TITLE
Publiser det ferskeste NiN-datasettet

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#24]

**Comment by bjornreppen** [comment]
Gjør jobben slik at det er mulig å repetere.

**Comment by jarped** [comment]
Blocked by https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/14

**Comment by jarped** [comment]
Nyeste NiN nå i vectorTiles

**Comment by bjornreppen** [comment]
Men hvor ligger filen?  Finner den ikke her? http://it-webadbtest01.it.ntnu.no/data/mbtiles/
