### ISSUE TITLE
Importjobb kodetre fra json

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#3]
- Lastejobben leser inn koder med tittel fra fil
- Setter inn kodene i postgresql basen og 
- Lager relasjoner i basen til foreldre slik at man kan spørre på 1 kode og få ut 1 rad per overordnet kode (+selv) uten å gjøre en rekursiv spørring

Kildefil: https://firebasestorage.googleapis.com/v0/b/grunnkart.appspot.com/o/koder%2Fkoder_med_forfedre.json?alt=media

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/d9d8cbf6e73b78d9ab4263df5b0b1b649bcb9db6
