### ISSUE TITLE
Tileset med høydedata

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#30]
Terrarium format PNG tiles containing raw elevation data in meters. All values are positive with a 32,768 offset, split into the red, green, and blue channels, with 16 bits of integer and 8 bits of fraction. To decode:
```
(red * 256 + green + blue / 256) - 32768
```
* Extension: png
* Projeksjon: Web Mercator
* Bitmap dimensjoner: 256x256

https://mapzen.com/documentation/terrain-tiles/formats/

Relatert til #31 Tileset med terreng-normaler

**Comment by jarped** [comment]
Antagelig noe mer småpuss som må til for å fikse null-verdier, men burde være nok for å teste med.

**Comment by jarped** [comment]
Mapbox hillshade fra høyde:
![image](https://user-images.githubusercontent.com/3570752/40786656-d90f70ee-64eb-11e8-8a71-0fed062fc195.png)

Mapzen hillshade fra høyde:
![image](https://user-images.githubusercontent.com/3570752/40786588-aa4d830e-64eb-11e8-95a7-fef823072479.png)
