### ISSUE TITLE
Labels på områder

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#32]
Navn på:
* Verneområder
* Fylker
* Kommuner

Eksportere i vector tiles slik at det blir synlig i kartet.

**Comment by jarped** [comment]
Related:
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/fb2cace6a74229a61fcb500907765580b394da12

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/dd8cb6149b3199f8f16bfc33a24efd7c786b5883
