### ISSUE TITLE
Map grunntyper over til kartleggingsnivå C

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#35]
Ingen grunntyper i eksporterte data, bare kategorisert ned til kartleggingsnivå.

Bruk [kverna/NA_grunntyper.json](https://github.com/Artsdatabanken/kverna/blob/master/kildedata/NA_grunntyper.json) for å mappe.

**Comment by jarped** [comment]
Skal være løst med ny datafil:
http://it-webadbtest01.it.ntnu.no/data/json/sqrt42/sqrt42bbox.json
