### ISSUE TITLE
Ukjente koder i codeBbox

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#36]
[codeBbox.json](http://it-webadbtest01.it.ntnu.no/data/geojson/codeBbox.geojson) inneholder koder som ikke finnes i typesystemet:
 * Natursystem grunntyper (se #35)
 * Miljøvariabler mangler prefiks (*MI*+*BS*)

**Comment by jarped** [comment]
Tror denne er gammel og skal erstattes av http://it-webadbtest01.it.ntnu.no/data/json/sqrt42/sqrt42bbox.json
