### ISSUE TITLE
Tileserver offline

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#43]
Lag et regime som gjør at tileserver kommer opp etter server restart og starter igjen etter feilsituasjoner.

Samt dokumenter i en .md hvordan det settes opp/henger sammen.

**Comment by jarped** [comment]
Skulle allerede vært fikset av https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/38

**Comment by jarped** [comment]
README ++
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/2e9fabc8b0557d8dd3d770420fc6cd2ddc6ef3d4
