### ISSUE TITLE
Ukjent kode i bbox  BS_3TO_B�

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#45]
Skulle det egentlig vært et annet tegn her enn "REPLACEMENT CHARACTER"?

![image](https://user-images.githubusercontent.com/281359/39856696-29284e50-5431-11e8-886c-545436b06798.png)

https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/16b3b4af8b28682c7cc5f9cef4068fd1296efb63

http://it-webadbtest01.it.ntnu.no/data/json/sqrt42/sqrt42bbox.json
