### ISSUE TITLE
Codes used as Foreign Keys must indicate so #114

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#48]
Polygoner med verneområder blir tagget med kommune og fylke.
Dette gjør at de aktiveres når man velger fylker/kommuner. 
Fjern fylke- og kommunetags på verneområder.

Relatert til [kverna/#114](https://github.com/Artsdatabanken/kverna/issues/114)

**Comment by jarped** [comment]
Det gjøres ingen eksplisitt tagging i import/database. Alt kommer fra kverna.
