### ISSUE TITLE
Importjobb kalkkart

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#5]
- Tagge områder med koder for kalkinnhold og bergarter
- Importere i basen

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/be790411222a3f76a667e95ca8aae03f09558429

**Comment by jarped** [comment]
Added separate issue for tagging:
https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/17
