### ISSUE TITLE
Lag en read-only bruker for ad-hoc bruk (QGIS ol.)

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/grunnkart-dataflyt#50]
PostgreSQL bruker som bare har lesetilgang.

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/blob/master/docker/postgis/init/3_reader.sql

og

https://github.com/Artsdatabanken/grunnkart-dataflyt/blob/master/docker/postgis/init/4_grant.sh
