### ISSUE TITLE
Legg til Andel  i Bigbadabom

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/grunnkart-dataflyt#57]
Ogapi skal bruke bigbadabom som datakilde, med trenger andel for naturområdetype

**Comment by bjornreppen** [comment]
Fordi?

**Comment by jarped** [comment]
https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/2179b47c1784d45e5cc24e21ac252f853c47a6f2 og https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/c1da2c7115ed68321564a1d362456166b473c795

**Comment by bjornreppen** [comment]
Bra at vi får ut areal igjen.
