### ISSUE TITLE
Lage mbtiles pr kode

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/grunnkart-dataflyt#64]
Vi går bort fra tagging og lager i stedet mbtiles pr kode. Disse innehoder kodens barn!

Ønskede attributter:
- [x] Kode (formateres som "Code": "NA_T", ikke som i dag, "NA_T": null)
- [x] Areal
- [x] Name (for kommuner verneområder etc)

Geometri aggregeres for kodens barn i henhold til hierarki

**Comment by bjornreppen** [comment]
Kan vi plugge denne inn i pipeline for å få ut metadata på tilesetta? https://www.npmjs.com/package/@artsdatabanken/dump-mbtiles-metadata

**Comment by jarped** [comment]
Ser nyttig ut, nice work!

Jarle

Sendt fra min iPhone
